//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maraphon_skills
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class marafonEntities : DbContext
    {
        public marafonEntities()
            : base("name=marafonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Charity> Charity { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<Event> Event { get; set; }
        public DbSet<EventType> EventType { get; set; }
        public DbSet<Gender> Gender { get; set; }
        public DbSet<Marathon> Marathon { get; set; }
        public DbSet<RaceKitOption> RaceKitOption { get; set; }
        public DbSet<Registration> Registration { get; set; }
        public DbSet<RegistrationEvent> RegistrationEvent { get; set; }
        public DbSet<RegistrationStatus> RegistrationStatus { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Runner> Runner { get; set; }
        public DbSet<Sponsorship> Sponsorship { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Volunteer> Volunteer { get; set; }
    }
}
