//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maraphon_skills
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public Registration()
        {
            this.RegistrationEvent = new HashSet<RegistrationEvent>();
            this.Sponsorship = new HashSet<Sponsorship>();
        }
    
        public int RegistrationId { get; set; }
        public int RunnerId { get; set; }
        public System.DateTime RegistrationDateTime { get; set; }
        public string RaceKitOptionId { get; set; }
        public byte RegistrationStatusId { get; set; }
        public decimal Cost { get; set; }
        public int CharityId { get; set; }
        public decimal SponsorshipTarget { get; set; }
    
        public virtual Charity Charity { get; set; }
        public virtual RaceKitOption RaceKitOption { get; set; }
        public virtual RegistrationStatus RegistrationStatus { get; set; }
        public virtual ICollection<RegistrationEvent> RegistrationEvent { get; set; }
        public virtual Runner Runner { get; set; }
        public virtual ICollection<Sponsorship> Sponsorship { get; set; }
    }
}
